services:
  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"
    networks:
      - mern
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    networks:
      - mern
  mongo:
    image: mongo:latest
    container_name: mongodb # Added container name for clear internal reference
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      # FIX IS HERE: Added '- ' before the volume mapping
      - mongo-data:/data/db 

networks:
  mern:
    driver: bridge
    
volumes:
  mongo-data: 
    driver: local